version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    networks:
      - my-network

  app-auth-service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app-auth-service
    restart: always
    depends_on:
      - redis
      - mongodb
    environment:
      - SERVICE_NAME=app-auth-service
      - MONGO_URI=mongodb://admin:adminpass@mongodb:27017/auth-db
      - REDIS_URL=redis://redis:6379
    ports:
      - '3002:3002'
    networks:
      - my-network

  user-service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: user-service
    restart: always
    depends_on:
      - mongodb
    environment:
      - SERVICE_NAME=user-service
      - MONGO_URI=mongodb://admin:adminpass@mongodb:27017/auth-db
      - REDIS_URL=redis://redis:6379
    ports:
      - '3001:3001'
    networks:
      - my-network

  user-api-gateway:
    build:
      context: .
      dockerfile: dockerfile
    container_name: user-api-gateway
    restart: always
    depends_on:
      - app-auth-service
      - user-service
    environment:
      - SERVICE_NAME=user-api-gateway
      - REDIS_URL=redis://redis:6379
    ports:
      - '3000:3000'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
