# Build stage
FROM node:18-alpine AS builder
WORKDIR /app

# Copy root package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# Copy the entire repository and build
COPY . .
RUN pnpm run build

# Final stage
FROM node:18-alpine
WORKDIR /app

# Adjust the path if your build output directory is different
COPY --from=builder /app/dist/apps/auth-service .

EXPOSE 3002
CMD ["node", "main.js"]
